# Generated by Django 5.1.5 on 2025-09-07 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(db_column='feed_id', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feed_images/', verbose_name='이미지')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '피드',
                'verbose_name_plural': '피드',
                'db_table': 'feed',
            },
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(db_column='planner_id', primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='지역')),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='planner_images/', verbose_name='일정 이미지')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
            ],
            options={
                'verbose_name': '여행 일정',
                'verbose_name_plural': '여행 일정',
                'db_table': 'planner',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='이메일')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Tourlist',
            fields=[
                ('id', models.AutoField(db_column='tourlist_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='관광지명')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('area_code', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='지역 코드')),
                ('sigungu_code', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='시군구 코드')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_images/', verbose_name='이미지')),
                ('read_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('pin_count', models.IntegerField(default=0, verbose_name='찜 수')),
            ],
            options={
                'verbose_name': '관광지 정보',
                'verbose_name_plural': '관광지 정보',
                'db_table': 'tourlist',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(db_column='reply_id', primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='작성일')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='planner.feed')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='planner.reply')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.signup')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'reply',
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.signup', verbose_name='작성자'),
        ),
        migrations.CreateModel(
            name='PlannerDetail',
            fields=[
                ('id', models.AutoField(db_column='planner_detail_id', primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=200, verbose_name='상세 일정명')),
                ('written_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='실제 날짜')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.planner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.signup')),
                ('tourlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.tourlist')),
            ],
            options={
                'verbose_name': '일정 상세',
                'verbose_name_plural': '일정 상세',
                'db_table': 'planner_detail',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(db_column='like_id', primary_key=True, serialize=False)),
                ('is_like', models.BooleanField(default=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='planner.feed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.signup')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요',
                'db_table': 'like',
                'constraints': [models.UniqueConstraint(fields=('feed', 'author'), name='unique_like')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(db_column='bookmark_id', primary_key=True, serialize=False)),
                ('is_marked', models.BooleanField(default=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='planner.feed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.signup')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크',
                'db_table': 'bookmark',
                'constraints': [models.UniqueConstraint(fields=('feed', 'author'), name='unique_bookmark')],
            },
        ),
    ]
